version: '3'

services:

  request:
    build:
      context: ./Services/request-service
      dockerfile: Dockerfile
    restart: unless-stopped
    depends_on: [mongo]
    environment:
      MONGO_URI: mongodb://${DB_USER}:${DB_PASSWD}@mongo:27017/?authMechanism=DEFAULT
      MONGO_COLLECTION: ${DB_COLLECTION}
      URL: ${URL}
      PYTHONUNBUFFERED: 1
    command: "python main.py ${SLEEP_TIME_IN_SECONDS}"
    tty: true

  api:
    build:
      context: ./Services/api-service
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - 5000:5000
    command: "python run.py"
    depends_on: [mongo]
    environment:
      MONGO_URI: mongodb://${DB_USER}:${DB_PASSWD}@mongo:27017/?authMechanism=DEFAULT
      DEFAULT_PAGE_SIZE: ${DEFAULT_PAGE_SIZE}
      # Para pruebas unitarias
      TEST_INIT_VALUE: ${TEST_INIT_VALUE}
      TEST_END_VALUE: ${TEST_END_VALUE}
      TEST_TIMESTAMP: ${TEST_TIMESTAMP}
      TEST_PAGE_VALUE: ${TEST_PAGE_VALUE}

  mongo:
    image: mongo:latest
    restart: unless-stopped
    ports:
      - 27017:27017
    volumes:
      - ./mongo_init.js:/docker-entrypoint-initdb.d/mongo-init.js
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASSWD}

  

    

      

